import { PrismaClient } from "@prisma/client";
import { TiposCurso } from "./tipo-curso";
import { AreasConhecimento } from "./areas-conhecimento";

const prisma = new PrismaClient();

export async function seedCursos() {
  const cursos = [
    /* Bacharelado */
    { id: 1, name: "Administração", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_SOCIAIS_APLICADAS },
    { id: 2, name: "Administração Pública", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_SOCIAIS_APLICADAS },
    { id: 3, name: "Agroecologia", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_AGRARIAS },
    { id: 4, name: "Agronegócio", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_AGRARIAS },
    { id: 5, name: "Agronomia", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_AGRARIAS },
    { id: 6, name: "Análise de Sistemas", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 7, name: "Antropologia", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_HUMANAS },
    { id: 8, name: "Arquitetura e Urbanismo", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 9, name: "Arquivologia", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_SOCIAIS_APLICADAS },
    { id: 10, name: "Artes", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.LINGUISTICA_LETRAS_E_ARTES },
    { id: 11, name: "Artes Cênicas", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.LINGUISTICA_LETRAS_E_ARTES },
    { id: 12, name: "Astronomia", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_EXATAS_E_DA_TERRA },
    { id: 13, name: "Biblioteconomia", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_SOCIAIS_APLICADAS },
    { id: 14, name: "Biologia", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_BIOLOGICAS },
    { id: 15, name: "Biomedicina", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_DA_SAUDE },
    { id: 16, name: "Bioquímica", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_BIOLOGICAS },
    { id: 17, name: "Canto", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.LINGUISTICA_LETRAS_E_ARTES },
    { id: 18, name: "Cenografia", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.LINGUISTICA_LETRAS_E_ARTES },
    { id: 19, name: "Ciência da Computação", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 20, name: "Ciências Biológicas", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_BIOLOGICAS },
    { id: 21, name: "Ciências Contábeis", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_SOCIAIS_APLICADAS },
    { id: 22, name: "Ciências Econômicas", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_SOCIAIS_APLICADAS },
    { id: 23, name: "Ciências Sociais", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_HUMANAS },
    { id: 24, name: "Cinema e Audiovisual", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.LINGUISTICA_LETRAS_E_ARTES },
    { id: 25, name: "Composição e Regência", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.LINGUISTICA_LETRAS_E_ARTES },
    { id: 26, name: "Computação", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 27, name: "Comunicação e Marketing", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_SOCIAIS_APLICADAS },
    { id: 28, name: "Comunicação Social", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_SOCIAIS_APLICADAS },
    { id: 29, name: "Desenho Industrial", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 30, name: "Design", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 31, name: "Design de Ambientes", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 32, name: "Design de Games", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 33, name: "Design de Interiores", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 34, name: "Design de Moda", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 35, name: "Design de Produto", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 36, name: "Design Digital", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 37, name: "Design Gráfico", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 38, name: "Direção", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.LINGUISTICA_LETRAS_E_ARTES },
    { id: 39, name: "Direito", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_SOCIAIS_APLICADAS },
    { id: 40, name: "Educação Física", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_DA_SAUDE },
    { id: 41, name: "Enfermagem", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_DA_SAUDE },
    { id: 42, name: "Engenharia Acústica", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 43, name: "Engenharia Aeroespacial", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 44, name: "Engenharia Aeronáutica", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 45, name: "Engenharia Agrícola", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_AGRARIAS },
    { id: 46, name: "Engenharia Agroindustrial", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_AGRARIAS },
    { id: 47, name: "Engenharia Agronômica", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_AGRARIAS },
    { id: 48, name: "Engenharia Ambiental", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_AGRARIAS },
    { id: 49, name: "Engenharia Automotiva", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 50, name: "Engenharia Bioenergética", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 51, name: "Engenharia Biomédica", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 52, name: "Engenharia Bioquímica", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 53, name: "Engenharia Biotecnológica", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 54, name: "Engenharia Cartográfica", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 55, name: "Engenharia Civil", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 56, name: "Engenharia da Computação", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 57, name: "Engenharia da Mobilidade", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 58, name: "Engenharia de Agrimensura", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 59, name: "Engenharia de Agronegócios", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_AGRARIAS },
    { id: 60, name: "Engenharia de Alimentos", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_AGRARIAS },
    { id: 61, name: "Engenharia de Aquicultura", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_AGRARIAS },
    { id: 62, name: "Engenharia de Automação", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 63, name: "Engenharia de Bioprocessos", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 64, name: "Engenharia de Biossistemas", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 65, name: "Engenharia de Biotecnologia", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 66, name: "Engenharia de Energia", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 67, name: "Engenharia de Gestão", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 68, name: "Engenharia de Informação", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 69, name: "Engenharia de Instrumentação, Automação e Robótica", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 70, name: "Engenharia de Manufatura", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 71, name: "Engenharia de Materiais", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 72, name: "Engenharia de Minas", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 73, name: "Engenharia de Pesca", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_AGRARIAS },
    { id: 74, name: "Engenharia de Petróleo", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 75, name: "Engenharia de Produção", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 76, name: "Engenharia de Recursos Hídricos", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 77, name: "Engenharia de Saúde e Segurança", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 78, name: "Engenharia de Sistemas", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 79, name: "Engenharia de Software", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 79, name: "Engenharia de Telecomunicações", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 80, name: "Engenharia de Transporte e Logística", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 81, name: "Engenharia Elétrica", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 82, name: "Engenharia Eletrônica", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 83, name: "Engenharia em Sistemas Digitais", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 84, name: "Engenharia Ferroviária e Metroviária", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 85, name: "Engenharia Física", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_EXATAS_E_DA_TERRA },
    { id: 86, name: "Engenharia Florestal", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_AGRARIAS },
    { id: 87, name: "Engenharia Geológica", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_EXATAS_E_DA_TERRA },
    { id: 88, name: "Engenharia Hídrica", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_EXATAS_E_DA_TERRA },
    { id: 89, name: "Engenharia Industrial", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 90, name: "Engenharia Mecânica", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 91, name: "Engenharia Mecatrônica", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 92, name: "Engenharia Metalúrgica", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 93, name: "Engenharia Naval", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 94, name: "Engenharia Química", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 95, name: "Engenharia Têxtil", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 96, name: "Estatística", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_EXATAS_E_DA_TERRA },
    { id: 97, name: "Farmácia", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_DA_SAUDE },
    { id: 98, name: "Filosofia", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_HUMANAS },
    { id: 99, name: "Física", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_EXATAS_E_DA_TERRA },
    { id: 100, name: "Fisioterapia", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_DA_SAUDE },
    { id: 101, name: "Fonoaudiologia", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_DA_SAUDE },
    { id: 102, name: "Geografia", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_HUMANAS },
    { id: 103, name: "Gestão Ambiental", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_AGRARIAS },
    { id: 104, name: "Gestão da Informação", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_SOCIAIS_APLICADAS },
    { id: 105, name: "Gestão de Políticas Públicas", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_SOCIAIS_APLICADAS },
    { id: 106, name: "Gestão de Serviços de Saúde", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_SOCIAIS_APLICADAS },
    { id: 107, name: "Gestão do Agronegócio", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_AGRARIAS },
    { id: 108, name: "Gestão Pública", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_SOCIAIS_APLICADAS },
    { id: 109, name: "História", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_HUMANAS },
    { id: 110, name: "Hotelaria", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_SOCIAIS_APLICADAS },
    { id: 111, name: "Jornalismo", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_SOCIAIS_APLICADAS },
    { id: 112, name: "Letras", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.LINGUISTICA_LETRAS_E_ARTES },
    { id: 113, name: "Marketing", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_SOCIAIS_APLICADAS },
    { id: 114, name: "Matemática", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_EXATAS_E_DA_TERRA },
    { id: 115, name: "Mecânica Industrial", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 116, name: "Medicina", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_DA_SAUDE },
    { id: 117, name: "Medicina Veterinária", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_DA_SAUDE },
    { id: 118, name: "Moda", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.LINGUISTICA_LETRAS_E_ARTES },
    { id: 119, name: "Música", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.LINGUISTICA_LETRAS_E_ARTES },
    { id: 120, name: "Nutrição", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_DA_SAUDE },
    { id: 121, name: "Odontologia", tipoCursoId: TiposCurso.BACHARELADO, areaConhecimentoId: AreasConhecimento.CIENCIAS_DA_SAUDE },
    /* Licenciatura */
    { id: 122, name: "Artes", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.LINGUISTICA_LETRAS_E_ARTES },
    { id: 123, name: "Artes Cênicas", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.LINGUISTICA_LETRAS_E_ARTES },
    { id: 124, name: "Artes Plásticas", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.LINGUISTICA_LETRAS_E_ARTES },
    { id: 125, name: "Artes Visuais", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.LINGUISTICA_LETRAS_E_ARTES },
    { id: 126, name: "Biologia", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.CIENCIAS_BIOLOGICAS },
    { id: 127, name: "Ciência da Computação", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 128, name: "Ciências Agrícolas", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.CIENCIAS_AGRARIAS },
    { id: 129, name: "Ciências da Natureza", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.CIENCIAS_EXATAS_E_DA_TERRA },
    { id: 130, name: "Ciências Exatas", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.CIENCIAS_EXATAS_E_DA_TERRA },
    { id: 131, name: "Ciências Sociais", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.CIENCIAS_SOCIAIS_APLICADAS },
    { id: 132, name: "Computação", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 133, name: "Desenho e Plástica", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.LINGUISTICA_LETRAS_E_ARTES },
    { id: 134, name: "Educação do Campo", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.CIENCIAS_HUMANAS },
    { id: 135, name: "Educação Especial", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.CIENCIAS_HUMANAS },
    { id: 136, name: "Educação Física", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.CIENCIAS_BIOLOGICAS },
    { id: 137, name: "Enfermagem", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.CIENCIAS_DA_SAUDE },
    { id: 138, name: "Filosofia", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.CIENCIAS_HUMANAS },
    { id: 139, name: "Física", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.CIENCIAS_EXATAS_E_DA_TERRA },
    { id: 140, name: "Geografia", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.CIENCIAS_HUMANAS },
    { id: 141, name: "História", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.CIENCIAS_HUMANAS },
    { id: 142, name: "Informática", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.ENGENHARIAS_E_TECNOLOGIA },
    { id: 143, name: "Letras", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.LINGUISTICA_LETRAS_E_ARTES },
    { id: 144, name: "Matemática", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.CIENCIAS_EXATAS_E_DA_TERRA },
    { id: 145, name: "Música", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.LINGUISTICA_LETRAS_E_ARTES },
    { id: 146, name: "Pedagogia", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.CIENCIAS_HUMANAS },
    { id: 147, name: "Programa Especial de Formação Pedagógica", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.CIENCIAS_HUMANAS },
    { id: 148, name: "Psicologia", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.CIENCIAS_SOCIAIS_APLICADAS },
    { id: 149, name: "Química", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.CIENCIAS_BIOLOGICAS },
    { id: 150, name: "Segunda licenciatura", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.CIENCIAS_HUMANAS },
    { id: 151, name: "Teatro", tipoCursoId: TiposCurso.LICENCIATURA, areaConhecimentoId: AreasConhecimento.LINGUISTICA_LETRAS_E_ARTES },
    /* Tecnólogo */
    { id: 152, name: 'Acupuntura', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.AMBIENTE_E_SAUDE },
    { id: 153, name: 'Agrimensura', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFRAESTRUTURA },
    { id: 154, name: 'Agrocomputação', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.RECURSOS_NATURAIS },
    { id: 155, name: 'Agroecologia', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.RECURSOS_NATURAIS },
    { id: 156, name: 'Agroindústria', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.RECURSOS_NATURAIS },
    { id: 157, name: 'Agronegócio', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 158, name: 'Agropecuária', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.RECURSOS_NATURAIS },
    { id: 159, name: 'Alimentos', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_ALIMENTICIA },
    { id: 160, name: 'Análise de Dados', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 161, name: 'Análise e Desenvolvimento de Sistemas', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 162, name: 'Apicultura e Meliponicultura', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.RECURSOS_NATURAIS },
    { id: 163, name: 'Aquicultura', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.RECURSOS_NATURAIS },
    { id: 164, name: 'Arqueologia', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.AMBIENTE_E_SAUDE },
    { id: 165, name: 'Arquitetura de Dados', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 166, name: 'Artes do Espetáculo', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 167, name: 'Artes e Mídias Digitais', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 168, name: 'Assessoria Executiva Digital', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 169, name: 'Atividades de Inteligência e Gestão de Sigilos', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.SEGURANCA },
    { id: 170, name: 'Auditoria em Saúde', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.AMBIENTE_E_SAUDE },
    { id: 171, name: 'Automação de Escritórios e Secretariado', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.CONTROLE_E_PROCESSOS_INDUSTRIAIS },
    { id: 172, name: 'Automação e Manufatura Digital', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_INDUSTRIAL },
    { id: 173, name: 'Automação Industrial', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_INDUSTRIAL },
    { id: 174, name: 'Banco de Dados', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 175, name: 'Big Data e Inteligência Analítica', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 176, name: 'Big Data no Agronegócio', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.RECURSOS_NATURAIS },
    { id: 177, name: 'Biocombustíveis', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_ALIMENTICIA },
    { id: 178, name: 'Bioenergia', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_ALIMENTICIA },
    { id: 179, name: 'Bioinformática', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 180, name: 'Biotecnologia', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.RECURSOS_NATURAIS },
    { id: 181, name: 'Blockchain e Criptografia Digital', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 182, name: 'Cafeicultura', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.RECURSOS_NATURAIS },
    { id: 183, name: 'Cibersegurança', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 184, name: 'Ciência de Dados', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 185, name: 'Cinema e Audiovisual', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 186, name: 'Coach Digital', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 187, name: 'Coaching e Mentoring', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 188, name: 'Coding', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 189, name: 'Comércio Exterior', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 190, name: 'Computação em Nuvem', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 191, name: 'Comunicação Assistiva', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 192, name: 'Comunicação Digital', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 193, name: 'Comunicação em Computação Gráfica', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 194, name: 'Comunicação em Mídias Digitais', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 195, name: 'Comunicação Institucional', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 196, name: 'Conservação e Restauro', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 197, name: 'Construção Civil', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFRAESTRUTURA },
    { id: 198, name: 'Construção de Edifícios', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFRAESTRUTURA },
    { id: 199, name: 'Construção Naval', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFRAESTRUTURA },
    { id: 200, name: 'Controle Ambiental', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.AMBIENTE_E_SAUDE },
    { id: 201, name: 'Controle de Obras', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFRAESTRUTURA },
    { id: 202, name: 'Cosmetologia e Estética', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 203, name: 'Cozinha Contemporânea', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_ALIMENTICIA },
    { id: 204, name: 'Data Science', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 205, name: 'Defesa Cibernética', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.SEGURANCA },
    { id: 206, name: 'Defesa Médica Hospitalar', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.AMBIENTE_E_SAUDE },
    { id: 207, name: 'Desenho de Animação', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 208, name: 'Desenvolvimento Back-End', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 209, name: 'Desenvolvimento de Aplicativos para Dispositivos Móveis', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 210, name: 'Desenvolvimento de Produtos Plásticos', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_INDUSTRIAL },
    { id: 211, name: 'Desenvolvimento de Sistemas', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 212, name: 'Desenvolvimento e Gestão de Startups', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 213, name: 'Desenvolvimento Mobile', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 214, name: 'Desenvolvimento para Internet', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 215, name: 'Desenvolvimento para Web', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 216, name: 'Design', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 217, name: 'Design Comercial', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 218, name: 'Design de Animação', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 219, name: 'Design de Aplicações e Interfaces Digitais', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 220, name: 'Design de Experiência e de Serviços', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 221, name: 'Design de Games', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 222, name: 'Design de Interiores', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 223, name: 'Design de Moda', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 224, name: 'Design de Produto', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN},
    { id: 225, name: 'Design Editorial', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 226, name: 'Design Educacional', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 227, name: 'Design Gráfico', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 228, name: 'Devops', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 229, name: 'Digital Influencer', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 230, name: 'Digital Security', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.SEGURANCA },
    { id: 231, name: 'E-Commerce', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 232, name: 'Educação e Processos de Trabalho: Alimentação Escolar', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.DESENVOLVIMENTO_EDUCACIONAL_E_SOCIAL },
    { id: 233, name: 'Educador Social', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.DESENVOLVIMENTO_EDUCACIONAL_E_SOCIAL },
    { id: 234, name: 'Eletrônica Automotiva', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_INDUSTRIAL },
    { id: 235, name: 'Eletrônica Industrial', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_INDUSTRIAL },
    { id: 236, name: 'Eletrotécnica Industrial', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_INDUSTRIAL },
    { id: 237, name: 'Embelezamento e Imagem Pessoal', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.AMBIENTE_E_SAUDE },
    { id: 238, name: 'Empreendedorismo', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 239, name: 'Energias Renováveis', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.RECURSOS_NATURAIS },
    { id: 240, name: 'Escrita Criativa', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 241, name: 'Estética e Cosmética', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.AMBIENTE_E_SAUDE },
    { id: 242, name: 'Estilismo', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 243, name: 'Estradas', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFRAESTRUTURA },
    { id: 244, name: 'Eventos', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 245, name: 'Fabricação Mecânica', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_INDUSTRIAL },
    { id: 246, name: 'Filmmaker', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 247, name: 'Finanças, Blockchain e Criptomoedas', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 248, name: 'Fitoterapia', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.AMBIENTE_E_SAUDE },
    { id: 249, name: 'Fotografia', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 250, name: 'Fruticultura', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.RECURSOS_NATURAIS },
    { id: 251, name: 'Futebol', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 252, name: 'Game Design', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 253, name: 'Gastronomia', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_ALIMENTICIA },
    { id: 254, name: 'Geoprocessamento', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 255, name: 'Gerenciamento de Redes de Computadores', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 256, name: 'Gerontologia', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.AMBIENTE_E_SAUDE },
    { id: 257, name: 'Gestão Ambiental', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.AMBIENTE_E_SAUDE },
    { id: 258, name: 'Gestão Comercial', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 259, name: 'Gestão Cultural', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 260, name: 'Gestão da Avaliação', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 261, name: 'Gestão da Inovação e Empreendedorismo Digital', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 262, name: 'Gestão da Produção Industrial', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_INDUSTRIAL },
    { id: 263, name: 'Gestão da Qualidade', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 264, name: 'Gestão da Segurança Pública e Patrimonial', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.SEGURANCA },
    { id: 265, name: 'Gestão das Organizações do Terceiro Setor', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 266, name: 'Gestão das Relações Eletrônicas', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 267, name: 'Gestão da Tecnologia da Informação', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 268, name: 'Gestão de Agronegócios', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.RECURSOS_NATURAIS },
    { id: 269, name: 'Gestão de Cidades Inteligentes', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 270, name: 'Gestão de Cloud Computing', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 271, name: 'Gestão de Cooperativas', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 272, name: 'Gestão de Inventário Extrajudicial', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 273, name: 'Gestão de Investimentos', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 274, name: 'Gestão de Lojas e Pontos de Vendas', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 275, name: 'Gestão de Mercado de Capitais', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 276, name: 'Gestão de Micro e Pequenas Empresas', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 277, name: 'Gestão de Negócios', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 278, name: 'Gestão de Pessoas', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 279, name: 'Gestão de Produção Industrial', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_INDUSTRIAL },
    { id: 280, name: 'Gestão de Qualidade na Saúde', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.AMBIENTE_E_SAUDE },
    { id: 281, name: 'Gestão de Recursos Hídricos', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.RECURSOS_NATURAIS },
    { id: 282, name: 'Gestão de Recursos Humanos', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 283, name: 'Gestão de Representação Comercial', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 284, name: 'Gestão de Resíduos de Serviços de Saúde', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.AMBIENTE_E_SAUDE },
    { id: 285, name: 'Gestão de Saúde Pública', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.AMBIENTE_E_SAUDE },
    { id: 286, name: 'Gestão de Segurança Privada', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.SEGURANCA },
    { id: 287, name: 'Gestão de Seguros', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 288, name: 'Gestão de Serviços Judiciários e Notariais', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 289, name: 'Gestão Desportiva e de Lazer', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.TURISMO_HOSPITALIDADE_E_LAZER },
    { id: 290, name: 'Gestão de Telecomunicações', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 291, name: 'Gestão de Trânsito', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFRAESTRUTURA },
    { id: 292, name: 'Gestão de Turismo', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.TURISMO_HOSPITALIDADE_E_LAZER },
    { id: 293, name: 'Gestão Empresarial', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 294, name: 'Gestão em Serviços', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 295, name: 'Gestão Financeira', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 296, name: 'Gestão Hospitalar', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.AMBIENTE_E_SAUDE },
    { id: 297, name: 'Gestão Portuária', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFRAESTRUTURA },
    { id: 298, name: 'Gestão Pública', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 299, name: 'Gestão Tributária', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 300, name: 'Horticultura', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.RECURSOS_NATURAIS },
    { id: 301, name: 'Hotelaria', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.TURISMO_HOSPITALIDADE_E_LAZER },
    { id: 302, name: 'Informática', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 303, name: 'Informática para Negócios', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 304, name: 'Instalações Elétricas', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFRAESTRUTURA },
    { id: 305, name: 'Instrumentação Cirúrgica', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.AMBIENTE_E_SAUDE },
    { id: 306, name: 'Inteligência Artificial', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 307, name: 'Interiores e Decorações', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 308, name: 'Internet das Coisas', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 309, name: 'Investigação e Perícia Criminal', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.SEGURANCA },
    { id: 310, name: 'Irrigação e Drenagem', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.RECURSOS_NATURAIS },
    { id: 311, name: 'Jogos Digitais', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFORMACAO_E_COMUNICACAO },
    { id: 312, name: 'Laticínios', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_ALIMENTICIA },
    { id: 313, name: 'Logística', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.CONTROLE_E_PROCESSOS_INDUSTRIAIS },
    { id: 314, name: 'Luteria', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_CULTURAL_E_DESIGN },
    { id: 315, name: 'Manufatura Avançada', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_INDUSTRIAL },
    { id: 316, name: 'Manutenção de Aeronaves', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.INFRAESTRUTURA },
    { id: 317, name: 'Manutenção Industrial', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.PRODUCAO_INDUSTRIAL },
    { id: 318, name: 'Marketing', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.GESTAO_E_NEGOCIOS },
    { id: 319, name: 'Massoterapia', tipoCursoId: TiposCurso.TECNOLOGO, areaConhecimentoId: AreasConhecimento.AMBIENTE_E_SAUDE},
  ];

  for(const curso of cursos) {
    await prisma.curso.upsert({
       where: { id: curso.id, tipoCursoId: curso.tipoCursoId, areaConhecimentoId: curso.areaConhecimentoId },
       create: curso,
       update: {name: curso.name},
     })
  };
  
  prisma.$disconnect();
  console.log("Cursos seed inserido com sucesso!");
}